#!/bin/bash

for dir in $(ls); do
    [ -d ${dir} ] || continue
    cd ${dir} || continue
    make clean > /dev/null 2>&1
    rm -rf CMakeFiles
    rm -f cmake_install.cmake CMakeCache.txt Makefile
    cd ..
done
